# Generated by Django 3.1.2 on 2020-10-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='Speciality',
        ),
    ]
