# Generated by Django 3.1.2 on 2020-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_name',
            new_name='key_settings',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_settings',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
