# Generated by Django 3.1.2 on 2020-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20201018_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
