# Generated by Django 3.1.2 on 2020-11-01 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20201030_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(default='no-image.png', upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(default='no-image.png', upload_to='speciality_images'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='published_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
